<template>
  <div class="spinner-container">
    <div class="spinner">
      <div v-for="(bar, index) of 8" :key="index"></div>
    </div>
  </div>
</template>
<script>
export default {
  name: "loaderSpinner",
};
</script>

<style scoped>
@keyframes spinner {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.spinner div {
  left: 46px;
  top: 27.5px;
  position: absolute;
  animation: spinner linear 1.01010101010101s infinite;
  background: #3b4368;
  width: 8px;
  height: 5px;
  border-radius: 2px / 2px;
  transform-origin: 4px 22.5px;
}
.spinner div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.8838383838383838s;
  background: #3b4368;
}
.spinner div:nth-child(2) {
  transform: rotate(45deg);
  animation-delay: -0.7575757575757575s;
  background: #3b4368;
}
.spinner div:nth-child(3) {
  transform: rotate(90deg);
  animation-delay: -0.6313131313131313s;
  background: #3b4368;
}
.spinner div:nth-child(4) {
  transform: rotate(135deg);
  animation-delay: -0.505050505050505s;
  background: #3b4368;
}
.spinner div:nth-child(5) {
  transform: rotate(180deg);
  animation-delay: -0.37878787878787873s;
  background: #3b4368;
}
.spinner div:nth-child(6) {
  transform: rotate(225deg);
  animation-delay: -0.2525252525252525s;
  background: #3b4368;
}
.spinner div:nth-child(7) {
  transform: rotate(270deg);
  animation-delay: -0.12626262626262624s;
  background: #3b4368;
}
.spinner div:nth-child(8) {
  transform: rotate(315deg);
  animation-delay: 0s;
  background: #3b4368;
}
.spinner-container {
  width: 35px;
  height: 35px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.spinner {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.35);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.spinner div {
  box-sizing: border-box;
}
/* generated by https://loading.io/ */
</style>
